### ISSUE TITLE
TODO: 0.1.2

### ISSUE THREAD

**Issue by domechn** [domechn/track3#12]
- [x] replace nodejs backend to rust
- [x] optmize 429 error when calling debank api
- [x] update style of historical data page
- [x] improve style of configuration page
- [x] fix: resize charts when windows size changes
