### ISSUE TITLE
TODO: 0.1.3

### ISSUE THREAD

**Issue by domechn** [domechn/track3#18]
- [x] local data encryption
- [x] auto update optimize
- [x] Chart of total value change of each coin
- [x] Chart of rise and fall percentage of each coin

research
- cloud data sync
