### ISSUE TITLE
TODO: 0.1.4

### ISSUE THREAD

**Issue by domechn** [domechn/track3#24]
- [x] optimize retry logic, save successful data in memory for 10min when retry
- [x] skip debank 429 error by use headless chrome
- [x] Each coin price changes chart
