### ISSUE TITLE
TODO: 0.1.5

### ISSUE THREAD

**Issue by domechn** [domechn/track3#31]
- [x] upgrade loading toast
- [x] support comparing assets between two dates
- [x] export and import data as json
- [x] refactor configuration page
- [x] fix: use pc local timezone
- [x] fix: wrong data type makes app crash
