### ISSUE TITLE
TODO: 0.1.1

### ISSUE THREAD

**Issue by domechn** [domechn/track3#4]
- [x] Support viewing historical data
- [x] Support deleting historical data
- [x] Support customize querying size 
- [x] Auto updater
