### ISSUE TITLE
TODO: 0.2.5

### ISSUE THREAD

**Issue by domechn** [domechn/track3#53]
- [x] download latest version background
- [ ] support mobile
- [x] delete data in cloud
- [x] arabic coin show error
<img width="373" alt="image" src="https://github.com/domechn/track3/assets/31119455/6a4582f3-5aee-442e-9894-fec91720471d">

- [ ] percentage of each wallet or cex account 
- [ ] emoji at the beginning of total value

**Comment by domechn** [comment]
move to project
