### ISSUE TITLE
TODO: 0.2.6

### ISSUE THREAD

**Issue by domechn** [domechn/track3#75]
- [ ] query assets by wallets
- [ ] wallets analyze
- [ ] quick action for comparison ( 1 week, 1 month, 1 quarter, 1 year )
- [ ] chart to show up and down percentage of each coin in 24h, 7d, 30d

**Comment by domechn** [comment]
move to project
